- Hestia/Hestia/Hestia.csproj
- Hestia/Hestia/backend/models/Activator.cs
- Hestia/Hestia/backend/models/deserializers/ActivatorDeserializer.cs
- Hestia/Hestia/backend/models/deserializers/DeviceDeserializer.cs
- Hestia/Hestia/packages.config
This PR adds the deserializers for Device and Activator
Useful for @daangroot : use DeviceDeserializer.deserializeDevices to instantly get a list of all the devices. (I think you want this for the server interactor
> Deserializers

- Hestia/Hestia/DevicesScreen/TableSource.cs
- Hestia/Hestia/DevicesScreen/UITableViewCellDevice.cs
- Hestia/Hestia/DevicesScreen/UITableViewControllerDevicesMain.cs
- Hestia/Hestia/backend/NetworkHandler.cs
- Hestia/Hestia/backend/models/Activator.cs
- Hestia/Hestia/backend/models/ActivatorState.cs
- Hestia/Hestia/backend/models/Device.cs
Begin integration with back end. Don't  know if I do it correctly
> Devices screen home. 

- Hestia/Hestia/AppDelegate.cs
- Hestia/Hestia/Hestia.csproj
- Hestia/Hestia/packages.config
Apparently app center analytics only work when we have certificates, because we have to sign the app. These certs will cost $99.99.......
> Remove app center analytics code

- Hestia/Hestia/DevicesScreen/TableSource.cs
- Hestia/Hestia/DevicesScreen/UITableViewControllerDevicesMain.cs
- Hestia/Hestia/Main.storyboard
- docs/time_tracking/s2380781.txt
The TableSource does not work yet, now trying to integrate with back end. The Switches part is throwing NullReferenceExceptions. I don't know where they come from. It worked fine with hardcoded data. But the integration needs some more systematic testing I think to sort it out, which is now too short time.  I am done for today.
> Code clean up devicesmain

- Hestia/Hestia/DevicesScreen/Devices1.storyboard
- Hestia/Hestia/DevicesScreen/SettingsController.cs
- Hestia/Hestia/DevicesScreen/SettingsController.designer.cs
- Hestia/Hestia/DevicesScreen/UITableViewControllerDevicesMain.cs
- Hestia/Hestia/DevicesScreen/UITableViewControllerServerConnect.cs
- Hestia/Hestia/DevicesScreen/resources/Globals.cs
- Hestia/Hestia/Hestia.csproj
Added a global variable class for the screens. Looked like a good solution for front end problem.
> completed functional connection screen. Just need to be able to check if server is valid.

- Hestia/Hestia/DevicesScreen/Devices1.storyboard
- Hestia/Hestia/DevicesScreen/TableSource.cs
I also adjusted the text alignment in the server connect screen such that it correctly displays on different screen formats. That should also be done with other screens.
> Switch can set state on server

- Hestia/Hestia/Hestia.csproj
- Hestia/Hestia/backend/utils/PingServer.cs
To be used when wanting to switch from server to server. This will check if the server is valid.
> Feature ping server

- Hestia/Hestia/Main.storyboard
I think this should fix the build error
> Removed unnecessary button from main storyboard

- Hestia/Hestia/Resources/strings.Designer.cs
- Hestia/Hestia/Resources/strings.resx
- Hestia/Hestia/backend/NetworkHandler.cs
- Hestia/Hestia/backend/ServerInteractor.cs
- Hestia/Hestia/backend/models/ActivatorState.cs
- Hestia/Hestia/backend/models/deserializers/ActivatorDeserializer.cs
- Hestia/Hestia/backend/models/deserializers/DeviceDeserializer.cs
This PR includes the backend fixes Feiko requested for sprint 3.
> Small fixes based on Feiko's feedback

- Hestia/Hestia/DevicesScreen/EditDevice/UIViewControllerEditDeviceName.cs
- Hestia/Hestia/DevicesScreen/TableSource.cs
- Hestia/Hestia/DevicesScreen/UITableViewControllerDevicesMain.cs
Fixed a bug that insert row was also clickable and that the wrong number of cells loaded on save button press
> Feiko comment's fixes and bug fixes for device screen

- Hestia/Hestia/Hestia.csproj
- Hestia/Hestia/backend/NetworkHandler.cs
- Hestia/Hestia/backend/ServerInteractor.cs
- Hestia/Hestia/backend/exceptions/ServerInteractionException.cs
I've added a new exception. This exception replaces the ServerException. When thrown it contains information about what went wrong.
> New custom exception for backend error handling.

- Hestia/Hestia/backend/models/Device.cs
This fixes the bug mentioned in #94.
> Fix bug when setting device name.

- Hestia/UnitTestHestia/UnitTestHestia.csproj
- Hestia/UnitTestHestia/backend/models/deserializers/ActivatorDeserializerTest.cs
- Hestia/UnitTestHestia/backend/models/deserializers/DeviceDeserializerTest.cs
- Hestia/UnitTestHestia/packages.config
Unit tests for deserializers in the backend
> Deserializer testing

- Hestia/Hestia/Hestia.csproj
- Hestia/Hestia/Info.plist
- Hestia/Hestia/LaunchScreen.storyboard
- Hestia/Hestia/Main.storyboard
- Hestia/Hestia/frontend/Devices2.storyboard
- Hestia/Hestia/frontend/Local/UITableViewControllerLocalLogin.cs
- Hestia/Hestia/frontend/Local/UITableViewControllerLocalLogin.designer.cs
- Hestia/Hestia/frontend/Local/UITableViewControllerServerConnect.cs
Changed the organization name to ruggedHestia.
Added local login screen.
Removed hardcoded Daan's server and created a boolean for debugging in that ServerConnectScreen.
Some code for signing with my AppleID is included, but this will change if someone else is going to sign with his AppleID.
Restored the launchscreen that was removed from the directory structure.
Also (temporarily) redirected back the settings screen server/login to the initial screen. Maybe a good solution ultimately.
> Preparing the app for putting it on device

- Hestia/Hestia/backend/models/Activator.cs
This should fix the bug which Marc mentioned on slack.
> Fix bug in activator state setter.

- Hestia/Hestia.UnitTests/Hestia.UnitTests.csproj
- Hestia/Hestia.UnitTests/backend/ServerInteractorTests.cs
- Hestia/Hestia.UnitTests/backend/models/DeviceTests.cs
- Hestia/Hestia.UnitTests/packages.config
- Hestia/Hestia/backend/NetworkHandler.cs
- Hestia/Hestia/backend/ServerInteractor.cs
- Hestia/Hestia/backend/models/deserializers/DeviceDeserializer.cs
NOTE: first review and merge #108 pls.
I've not written tests for the methods Equals(), GetHashCode() and ToString() yet, because I'm not sure if the front end uses them, @MarcF12 probably knows :)
> Added unit tests for the device class

- Hestia/Hestia.UnitTests/Hestia.UnitTests.csproj
- Hestia/Hestia.UnitTests/backend/ServerInteractorTests.cs
- Hestia/Hestia.UnitTests/backend/models/DeviceTests.cs
- Hestia/Hestia.UnitTests/backend/models/PluginInfoTests.cs
- Hestia/Hestia.UnitTests/packages.config
- Hestia/Hestia/backend/NetworkHandler.cs
- Hestia/Hestia/backend/ServerInteractor.cs
- Hestia/Hestia/backend/models/deserializers/DeviceDeserializer.cs
> Plugin info unit testing

- Hestia/Hestia/Hestia.csproj
- Hestia/Hestia/Main.storyboard
- Hestia/Hestia/backend/ServerInteractor.cs
- Hestia/Hestia/frontend/Devices2.storyboard
- Hestia/Hestia/frontend/Devices3.storyboard
- Hestia/Hestia/frontend/DevicesScreen/AddDeviceScreen/TableSourceAddDeviceDevice.cs
- Hestia/Hestia/frontend/DevicesScreen/AddDeviceScreen/UITableViewControllerAddDevice.cs
- Hestia/Hestia/frontend/DevicesScreen/AddDeviceScreen/UITableViewControllerAddDeviceProperties.cs
- Hestia/Hestia/frontend/DevicesScreen/TableSourceDevicesMain.cs
- Hestia/Hestia/frontend/DevicesScreen/UITableViewControllerDevicesMain.cs
- Hestia/Hestia/frontend/Firebase/TableSourceAddDeviceChooseServer.cs
- Hestia/Hestia/frontend/Firebase/UITableViewControllerAddDeviceChooseServer.cs
- Hestia/Hestia/frontend/Firebase/UITableViewServerList.cs
- Hestia/Hestia/frontend/Firebase/UIViewControllerGlobalLogin.cs
- Hestia/Hestia/frontend/Firebase/UIViewControllerGlobalLogin.designer.cs
- Hestia/Hestia/frontend/Local/UITableViewControllerLocalLogin.cs
- Hestia/Hestia/frontend/Local/UITableViewControllerServerConnect.cs
- Hestia/Hestia/frontend/resources/Globals.cs
This links the server select screen and the device main screen. Deleting a device is not yet possible with multiple servers, I will work on that.
> Combine server bundling

- Hestia/Hestia.UnitTests/Hestia.UnitTests.csproj
- Hestia/Hestia.UnitTests/backend/NetworkHandlerTests.cs
- Hestia/Hestia.UnitTests/backend/exceptions/ServerInteractionExceptionTests.cs
- Hestia/Hestia.UnitTests/backend/models/ActivatorTests.cs
- Hestia/Hestia.UnitTests/backend/models/deserializers/ActivatorDeserializerTests.cs
- Hestia/Hestia.UnitTests/backend/models/deserializers/DeviceDeserializerTests.cs
- Hestia/Hestia.UnitTests/backend/utils/JsonValidatorTests.cs
- Hestia/Hestia.UnitTests/backend/utils/PingServerTests.cs
- Hestia/Hestia/backend/models/Activator.cs
All new tests passed. I also resolved a bug in the `State` setter in `Activator.cs` (exception wasn't rethrown).
> Added unit tests for jsonvalidator, activator and serverinteractionexception

- Hestia/Hestia.UnitTests/backend/models/deserializers/ActivatorDeserializerTests.cs
- Hestia/Hestia.UnitTests/backend/models/deserializers/DeviceDeserializerTests.cs
- Hestia/Hestia/backend/models/Device.cs
- Hestia/Hestia/backend/models/deserializers/ActivatorDeserializer.cs
- Hestia/Hestia/backend/models/deserializers/DeviceDeserializer.cs
Also fixed a bug in the activator state.
> Fixed and extended deserializers unit tests.

- docs/time_tracking/s3178900.txt
seems to rewrite the entire thing, no problemo I suppose.
> Added my time

- README.md
> Should make a line break and fix the issue.

- Hestia/Hestia/backend/NetworkHandler.cs
- Hestia/Hestia/backend/ServerInteractor.cs
- Hestia/Hestia/backend/models/Activator.cs
- Hestia/Hestia/backend/models/ActivatorState.cs
- Hestia/Hestia/backend/models/Device.cs
- Hestia/Hestia/backend/models/PluginInfo.cs
Made some getters and setters in backend more compact as Feiko requested.
> Make getters and setters more compact.

- Hestia/Hestia/frontend/Devices2.storyboard
- Hestia/Hestia/frontend/DevicesScreen/AddDeviceScreen/PropertyCell.cs
- Hestia/Hestia/frontend/DevicesScreen/AddDeviceScreen/TableSourceAddDeviceProperties.cs
- Hestia/Hestia/frontend/DevicesScreen/AddDeviceScreen/UITableViewControllerAddDeviceProperties.cs
- Hestia/Hestia/frontend/DevicesScreen/EditDevice/UIViewControllerEditDeviceName.cs
- Hestia/Hestia/frontend/DevicesScreen/UITableViewControllerDevicesMain.cs
Background color for edit device screen and add a new device screen fixed.
> Fixing background color

- Hestia/Hestia/backend/HestiaServerInteractor.cs
- Hestia/Hestia/backend/HestiaWebServerInteractor.cs
- Hestia/Hestia/backend/NetworkHandler.cs
- Hestia/Hestia/frontend/EntryScreen/UIViewControllerLocalGlobal.cs
All methods in `HestiaServerInteractor.cs` do work now with auth0. I've also added a method to add a new server.
> Fix remote server back end code

- docs/time_tracking/s3254518.txt
PR that updates my time tracking file.
Also updated the architecture document, but it's best to merge the new version exactly before the sprint instead of now already, since it could be possible that people are still updating it.
> Time tracking update, documents update

- Hestia/Hestia.UnitTests/backend/HestiaServerInteractorTests.cs
- Hestia/Hestia.UnitTests/backend/HestiaWebServerInteractorTests.cs
- Hestia/Hestia.UnitTests/backend/NetworkHandlerTests.cs
- Hestia/Hestia.UnitTests/backend/models/ActivatorTests.cs
- Hestia/Hestia.UnitTests/backend/models/DeviceTests.cs
- Hestia/Hestia.UnitTests/backend/models/HestiaServerTests.cs
- Hestia/Hestia.UnitTests/backend/models/deserializers/DeviceDeserializerTests.cs
- Hestia/Hestia.UnitTests/backend/models/deserializers/HestiaServerDeserializerTests.cs
- Hestia/Hestia/backend/NetworkHandler.cs
#223 broke quite some unit tests, they are fixed now.
> Fix broken back end unit tests

- Hestia/Hestia/backend/HestiaServerInteractor.cs
- Hestia/Hestia/backend/HestiaWebServerInteractor.cs
- Hestia/Hestia/backend/NetworkHandler.cs
- Hestia/Hestia/backend/authentication/Auth0Connector.cs
- Hestia/Hestia/backend/exceptions/ServerInteractionException.cs
- Hestia/Hestia/backend/models/Activator.cs
- Hestia/Hestia/backend/models/ActivatorState.cs
- Hestia/Hestia/backend/models/Device.cs
- Hestia/Hestia/backend/models/HestiaServer.cs
- Hestia/Hestia/backend/models/PluginInfo.cs
- Hestia/Hestia/backend/models/deserializers/ActivatorDeserializer.cs
- Hestia/Hestia/backend/models/deserializers/DeviceDeserializer.cs
- Hestia/Hestia/backend/models/deserializers/HestiaServerDeserializer.cs
- Hestia/Hestia/backend/speech_recognition/IViewControllerSpeech.cs
- Hestia/Hestia/backend/speech_recognition/SpeechRecognition.cs
- Hestia/Hestia/backend/utils/JsonValidator.cs
- Hestia/Hestia/backend/utils/PingServer.cs
- Hestia/Hestia/frontend/DevicesScreen/UITableViewControllerDevicesMain.cs
Also removed some unused imports and methods.
> Back end code documentation

- Hestia/Hestia.UnitTests/backend/NetworkHandlerTests.cs
Removed no longer required test.
> Fix build error
